"""Add S3 key column to fcs_files table

Revision ID: f4112605d95d
Revises: 092773789ded
Create Date: 2025-10-17 23:04:34.382231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'f4112605d95d'
down_revision: Union[str, None] = '092773789ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcs_files', sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'fcs_files', ['s3_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fcs_files', type_='unique')
    op.drop_column('fcs_files', 's3_key')
    # ### end Alembic commands ###
