"""Add public column to fcs_files table

Revision ID: 601a292b2a04
Revises: 9e546b1ef3a0
Create Date: 2025-10-18 16:52:20.275559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '601a292b2a04'
down_revision: Union[str, None] = '9e546b1ef3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcs_files', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fcs_files', 'public')
    # ### end Alembic commands ###
