"""Rename job_kwargs to job_args

Revision ID: db77633993ae
Revises: 586261512215
Create Date: 2025-10-19 22:47:26.841074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'db77633993ae'
down_revision: Union[str, None] = '586261512215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_kwargs', new_column_name='job_args')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_args', new_column_name='job_kwargs')
    # ### end Alembic commands ###
