"""Make job_type string

Revision ID: b4044b3ba4da
Revises: d7d6a064e639
Create Date: 2025-10-19 17:04:37.169237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'b4044b3ba4da'
down_revision: Union[str, None] = 'd7d6a064e639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_type',
               existing_type=postgresql.ENUM('FILES_STAT', 'FCS_INFO', name='jobtypeenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('FILES_STAT', 'FCS_INFO', name='jobtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
