"""Add jobs table

Revision ID: 91bd5e9fa8c4
Revises: cf880c3c9dd3
Create Date: 2025-10-19 16:22:48.622769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '91bd5e9fa8c4'
down_revision: Union[str, None] = 'cf880c3c9dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_job_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.Enum('FILES_STAT', 'FCS_INFO', name='jobtypeenum'), nullable=False),
    sa.Column('job_kwargs', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
