"""Add upload_bathces table and fcs_files table

Revision ID: 092773789ded
Revises: 
Create Date: 2025-10-17 01:38:00.110808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '092773789ded'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_idno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_idno')
    )
    op.create_table('fcs_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_idno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_byte', sa.Integer(), nullable=False),
    sa.Column('upload_batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_idno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcs_files')
    op.drop_table('upload_batches')
    # ### end Alembic commands ###
