"""Add users table

Revision ID: 00e25c5f5843
Revises: a0c39c8a8a81
Create Date: 2025-10-18 10:19:33.332961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '00e25c5f5843'
down_revision: Union[str, None] = 'a0c39c8a8a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
