"""Link jobs table and users table

Revision ID: d7d6a064e639
Revises: 91bd5e9fa8c4
Create Date: 2025-10-19 16:28:41.776875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'd7d6a064e639'
down_revision: Union[str, None] = '91bd5e9fa8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
