"""Link users table and fcs_files table

Revision ID: cf880c3c9dd3
Revises: 601a292b2a04
Create Date: 2025-10-18 17:08:31.290959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'cf880c3c9dd3'
down_revision: Union[str, None] = '601a292b2a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcs_files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fcs_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fcs_files', type_='foreignkey')
    op.drop_column('fcs_files', 'user_id')
    # ### end Alembic commands ###
