# Start from the official Python base image.
FROM public.ecr.aws/docker/library/python:3.12-slim

# Set the current working directory to /code.
WORKDIR /code

# Copy the file with the requirements to the /code directory.
COPY ./requirements.txt /code/requirements.txt

# Install the package dependencies in the requirements file.
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the ./app directory inside the /code directory.
COPY ./jobs /code/app

# Log 會輸出到 stdout 和 stderr 給 Docker，也會以檔案形式存在容器內，但會隨容器更新而消滅。
COPY ./logs /code/logs

# Set the **command** to use fastapi run, which uses Uvicorn underneath.
# CMD ["rq", "worker", "default"]
CMD ["python", "-m", "jobs"]
